### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by cmbant** [conda-forge/getdist-feedstock#8]
### Comment:

Is there a reason to have a conda-forge package for this, given getdist is pure python? 
If it's going to cause conflicts after updates, it would be nice to at least have it set to auto-merge so it updates quickly and automatically.

"packaging" should also be added to meta.yaml as reported by the autobot. Perhaps you could also add me to maintainers, so I can if necessary fix updates myself.

Thanks,
Antony

**Comment by vitenti** [comment]
Hi Antony,

Regarding our packaging for https://github.com/LSSTDESC/firecrown, we exclusively utilize conda-forge for all prerequisites due to the presence of compiled extensions in many of them. We avoid mixing with `pip` for two reasons: it complicates consistent environment updates, and package updates may introduce additional prerequisites with compiled code.

To address this, we have created conda-forge packages for all (almost all) prerequisites, including this one. We've designated this package as noarch since it lacks any architecture-dependent code.

I will add you as a maintainer so that you can implement any necessary updates or modifications.

Best,
Sandro

**Comment by vitenti** [comment]
@cmbant I just added you as a maintainer, tell me if you have further questions so I can close this issue.

**Comment by cmbant** [comment]
Thanks
